### ISSUE TITLE
Plugin not working with Libre Form 2.0.0

### ISSUE THREAD

**Issue by ondics** [k1sul1/wplf-export#6]
After installing this plugin via Plugin upload in Wordpress, nothing happens.

Wordpress: 6.2.2
Libre Form: 2.0.0

What am I missing here? Is this plugin still maintained?

**Comment by k1sul1** [comment]
There's really nothing to maintain in this plugin. The last commit was 6 years ago, which was way before 2.0 was even a thought in my mind. Why would it work with 2.0, which says it's backwards incompatible and rebuilt from scratch? :) 

Personally, I haven't needed needed this feature after I built it. One client wanted it, rest are quite happy with the emails or custom integrations to other systems. 

The equivalent of this plugin in 2.0 would be; 

```sql
SELECT * FROM wp_wplf_whatever;
```

That's dirty, but it works if you want the raw data. 

On the PHP side, in 2.x, there's WPLF\Form and WPLF\Submission classes, and a bunch of IO methods to go with them. There's also a REST API endpoint for the submissions which is used internally to view submissions. 

If you care about having an UI export, feel free to send a PR into https://github.com/libreform/libreform. The main branch is currently sitting at an unreleased 2.1, which improves the submission view alongside supporting multiple emails in a... hacky way. 

I think there's room for an "export" button in the toolbar that appears when you select a submission.
https://github.com/libreform/libreform/blob/master/assets/scripts/react/SubmissionList.tsx

That probably shouldn't be the only way to export submissions though, because that list requires you to scroll though all of your submissions in order to select them all. One of my clients has ~10 000 submissions to date, so naturally scrolling that is not an option. 

Having said that, you could forgo the React part entirely and... I don't know, add a subpage "Export" to this? 

![image](https://github.com/libreform/export/assets/2719615/552b3d59-a8d1-40fe-80c4-1cc82f0abec3)

You could reuse some of the code in this plugin. Submissions work differently in 2.0 than 1.0, so they don't have bulk actions, but the way CSVs are generated and downloaded hasn't changed one bit. You could even do one better and do it all in memory, to please the few people that host WP in environments where WP can't write to disk. It's up to you :)

**Comment by k1sul1** [comment]
I'll add; I don't want to publish another version of this plugin, that would somehow work with 1.x and 2.x. If you take a shot at it, use the master branch of the plugin as a base.

It's possible to make this work with both, but it doesn't make any sense when the only things that are the same in 1.x and 2.x is the name and the liberty of using pretty much any HTML and not have WordPress fuck with it. 

I think it'd make sense adding this feature in 2.x core, but maybe as an internal addon. The reasoning behind that is I don't want to have another way of accessing the data enabled by default. Some of my clients have quite delicate setups in regards to who can see what as the data is quite sensitive. The export functionality wouldn't have the same access control, I'd have to setup it, and get permission to ~~build~~ bill it -> I don't want to go changing any defaults 🙂
